Algoritmo "varieveis"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/04/2020
Var
   // Seção de Declarações das variáveis
   num,idade:inteiro
   frase:caracter

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Num <-10
   idade:=20
   frase:= "testando"
escreval(idade)
escreval(frase)
Fimalgoritmo